# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSnippet',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('code', models.TextField()),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.UserProfile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Language')),
            ],
            options={
                'verbose_name': 'historical snippet',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('code', models.TextField()),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snipes', to='account.UserProfile')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snipes', to='core.Language')),
            ],
        ),
    ]
