# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSnippet',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('language', models.IntegerField(choices=[(1, 'C#'), (2, 'PowerShell'), (3, 'C++'), (4, 'Python'), (5, 'Rust'), (6, 'JavaScript'), (7, 'CSS')], default=1)),
                ('code', models.TextField()),
                ('uid', models.CharField(max_length=32)),
                ('is_private', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.UserProfile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical snippet',
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('language', models.IntegerField(choices=[(1, 'C#'), (2, 'PowerShell'), (3, 'C++'), (4, 'Python'), (5, 'Rust'), (6, 'JavaScript'), (7, 'CSS')], default=1)),
                ('code', models.TextField()),
                ('uid', models.CharField(max_length=32)),
                ('is_private', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet', to='account.UserProfile')),
            ],
        ),
    ]
