# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsnippet',
            name='is_private',
            field=models.CharField(choices=[('PUBLIC', 'Visible to Everyone'), ('PRIVATE', 'Visible to Just Me'), ('LINK', 'Visible to People with Link')], default='PUBLIC', max_length=16),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='is_private',
            field=models.CharField(choices=[('PUBLIC', 'Visible to Everyone'), ('PRIVATE', 'Visible to Just Me'), ('LINK', 'Visible to People with Link')], default='PUBLIC', max_length=16),
        ),
    ]
