# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_auto_20170221_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsnippet',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='historicalsnippet',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snipes', to='account.UserProfile'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snipes', to='core.Language'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
