# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippet', '0004_auto_20170627_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='snippet.Snippet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_snipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
