# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0006_snippetsearchupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetsearchupdate',
            name='snippet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippet.Snippet'),
        ),
    ]
