# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippet', '0009_auto_20170725_2227'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set([('snippet', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='snippetviews',
            unique_together=set([('snippet', 'user')]),
        ),
    ]
