# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0010_auto_20170725_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmarked_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
