# Generated by Django 2.1.3 on 2018-11-08 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0011_bookmark_bookmarked_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsnippet',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsnippet',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='snipes', to='core.Language'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='snippetsearchupdate',
            name='snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snippet.Snippet'),
        ),
        migrations.AlterField(
            model_name='snippetviews',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_snipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
