# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='css_style',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='extensions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
