# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170625_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='full_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
