# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organisation',
        ),
        migrations.AddField(
            model_name='snipeuser',
            name='department',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='snipeuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
