# Generated by Django 2.1.3 on 2018-11-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170725_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snipeuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
