# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170302_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snipeuser',
            name='object_id',
        ),
    ]
